###
POST http://localhost:8322/pressureTest/getUserList
Content-Type: application/json
Content-Encoding: UTF-8
TRACE: a13
xs: for_test_only

{
  "startVersion": 1,
  "endVersion":10
}

<> 2023-07-19T194928.415.json